### ISSUE TITLE
Sample code is not deployed when installing the package through VCC

### ISSUE THREAD

**Issue by Thelvaen** [CyanLaser/CyanPlayerObjectPool#11]
Hello,

I just installed the package through VCC, and when reading the doc, it's mentioning templates & examples that were not deployed by VCC (I found them here), but I would have preferred to get them directly in the package with VCC.

Thanks for your feedback :)

Regards,
Thelvaen

**Comment by CyanLaser** [comment]
This is by design. VCC does not provide any way for package creators to auto import examples. The VRChat docs mention using the Unity Package Manager to import these into your project.
https://vcc.docs.vrchat.com/guides/finding-the-samples#other-package-samples

The issue with auto importing all examples for this package is that there are three different versions of the exact same examples, one per compiler. Since I don't want to bloat user projects with items I know won't be used, I let the user pick which compiler example they intend to work with.
